AWSTemplateFormatVersion: "2010-09-09"
Description: Creates the GOCD EC2 instance. This assumes a default VPC present with public subnets.

Parameters:
  security-key-name:
    Type: String
    Description: The SSH key name

Mappings:
  amiMap:
    regionWise:
      us-east-1: ami-97785bed
      us-east-2: ami-f63b1193
      us-west-2: ami-f2d3638a
      us-west-1: ami-824c4ee2
      ap-southeast-1: ami-68097514
      ap-southeast-2: ami-942dd1f6
      ap-south-1: ami-531a4c3c
      cn-north-1: ami-cb19c4a6


Resources:
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: GOCD-Box-SecurityGroup
      GroupDescription: Allows SSH and 8154 port access to the GOCD box from the world.
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '8154'
        ToPort: '8154'
        CidrIp: 0.0.0.0/0

  EC2:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref security-key-name
      ImageId: !FindInMap [amiMap, regionWise, !Ref "AWS::Region"]
      #need to change the below to a m5.large
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref SecurityGroup
      UserData:
        Fn::Base64:                               
          !Sub |
              #!/bin/bash -ex
              yum update
              yum install -y docker
              usermod -a -G docker ec2-user
              curl -L https://github.com/docker/compose/releases/download/1.9.0/docker-compose-`uname -s`-`uname -m` | sudo tee /usr/local/bin/docker-compose > /dev/null
              chmod +x /usr/local/bin/docker-compose
              service docker start
              chkconfig docker on
              
  EBS:
    Type: AWS::EC2::Volume
    Properties:
      Size: 8
      AvailabilityZone: !GetAtt EC2.AvailabilityZone

  MountPoint:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref EC2
      VolumeId: !Ref EBS
      Device: /dev/sdh